"""
SOP Document Export — Generate a professional .docx Operations Order.

POST /api/export/sop with the SOP JSON body.
Returns a downloadable .docx file.
"""
import io
from datetime import datetime
from docx import Document
from docx.shared import Inches, Pt, RGBColor, Emu
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.enum.table import WD_TABLE_ALIGNMENT
from docx.enum.section import WD_ORIENT


def build_sop_docx(sop: dict, event: dict = None, zones: list = None) -> io.BytesIO:
    """Build a formatted .docx from SOP data and return as BytesIO buffer."""
    doc = Document()

    # -- Page setup: US Letter, 1" margins --
    for sect in doc.sections:
        sect.page_width = Inches(8.5)
        sect.page_height = Inches(11)
        sect.top_margin = Inches(1)
        sect.bottom_margin = Inches(0.75)
        sect.left_margin = Inches(1)
        sect.right_margin = Inches(1)

    # -- Styles --
    style = doc.styles["Normal"]
    style.font.name = "Calibri"
    style.font.size = Pt(11)
    style.font.color.rgb = RGBColor(0x2C, 0x25, 0x20)
    style.paragraph_format.space_after = Pt(4)
    style.paragraph_format.line_spacing = 1.15

    # -- Color constants --
    DARK = RGBColor(0x2C, 0x25, 0x20)
    ACCENT = RGBColor(0xB8, 0x5C, 0x1F)
    BLUE = RGBColor(0x3D, 0x6B, 0x8E)
    MUTED = RGBColor(0x6B, 0x5E, 0x52)
    WHITE = RGBColor(0xFF, 0xFF, 0xFF)

    def add_heading_styled(text, level=1):
        h = doc.add_heading(text, level=level)
        for run in h.runs:
            run.font.color.rgb = DARK if level > 1 else ACCENT
            run.font.name = "Calibri"
        return h

    def add_para(text, bold=False, italic=False, color=None, size=None, space_after=None):
        p = doc.add_paragraph()
        run = p.add_run(text)
        run.font.name = "Calibri"
        if bold:
            run.bold = True
        if italic:
            run.italic = True
        if color:
            run.font.color.rgb = color
        if size:
            run.font.size = Pt(size)
        if space_after is not None:
            p.paragraph_format.space_after = Pt(space_after)
        return p

    def add_field(label, value, p=None):
        """Add a label: value line."""
        if p is None:
            p = doc.add_paragraph()
        run_label = p.add_run(label + ": ")
        run_label.bold = True
        run_label.font.name = "Calibri"
        run_label.font.size = Pt(11)
        run_label.font.color.rgb = DARK
        run_val = p.add_run(str(value) if value else "N/A")
        run_val.font.name = "Calibri"
        run_val.font.size = Pt(11)
        run_val.font.color.rgb = MUTED
        return p

    def add_bullet(text):
        p = doc.add_paragraph(text, style="List Bullet")
        for run in p.runs:
            run.font.name = "Calibri"
            run.font.size = Pt(11)
        return p

    def add_divider():
        p = doc.add_paragraph()
        p.paragraph_format.space_before = Pt(6)
        p.paragraph_format.space_after = Pt(6)
        run = p.add_run("_" * 72)
        run.font.color.rgb = RGBColor(0xE2, 0xDC, 0xD2)
        run.font.size = Pt(8)

    # ================================================================
    # TITLE PAGE
    # ================================================================
    for _ in range(4):
        doc.add_paragraph()

    title = doc.add_paragraph()
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = title.add_run("OPERATIONS ORDER")
    run.font.size = Pt(28)
    run.font.color.rgb = ACCENT
    run.bold = True
    run.font.name = "Calibri"

    subtitle = doc.add_paragraph()
    subtitle.alignment = WD_ALIGN_PARAGRAPH.CENTER
    evt = event or sop.get("event", {})
    evt_name = evt.get("name", "Disaster Event")
    evt_type = evt.get("type", "")
    declaration = evt.get("declaration", "")
    run = subtitle.add_run(f"{evt_type} {evt_name}")
    run.font.size = Pt(18)
    run.font.color.rgb = DARK
    run.font.name = "Calibri"

    if declaration:
        decl_para = doc.add_paragraph()
        decl_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
        run = decl_para.add_run(declaration)
        run.font.size = Pt(14)
        run.font.color.rgb = MUTED
        run.font.name = "Calibri"

    doc.add_paragraph()
    date_para = doc.add_paragraph()
    date_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = date_para.add_run(f"Generated: {datetime.now().strftime('%B %d, %Y %H:%M')}")
    run.font.size = Pt(11)
    run.font.color.rgb = MUTED
    run.font.name = "Calibri"

    gen_para = doc.add_paragraph()
    gen_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = gen_para.add_run("Generated by OpsPlan AI — Team Rubicon")
    run.font.size = Pt(10)
    run.font.color.rgb = BLUE
    run.font.name = "Calibri"

    doc.add_page_break()

    # ================================================================
    # I. SITUATION
    # ================================================================
    sit = sop.get("situation", {})
    add_heading_styled("I. Situation", level=1)

    add_heading_styled("Event Summary", level=2)
    add_para(sit.get("event_summary", "N/A"))

    add_heading_styled("Affected Area", level=2)
    add_para(sit.get("affected_area", "N/A"))

    add_heading_styled("Impact Summary", level=2)
    add_para(sit.get("impact_summary", "N/A"))

    add_heading_styled("Key Vulnerabilities", level=2)
    for v in sit.get("key_vulnerabilities", []):
        add_bullet(v)

    add_divider()

    # ================================================================
    # II. MISSION
    # ================================================================
    mis = sop.get("mission", {})
    add_heading_styled("II. Mission", level=1)

    add_heading_styled("Primary Objective", level=2)
    add_para(mis.get("primary_objective", "N/A"))

    add_heading_styled("Secondary Objectives", level=2)
    for o in mis.get("secondary_objectives", []):
        add_bullet(o)

    add_heading_styled("End State", level=2)
    add_para(mis.get("end_state", "N/A"))

    add_divider()

    # ================================================================
    # III. EXECUTION
    # ================================================================
    exe = sop.get("execution", {})
    add_heading_styled("III. Execution", level=1)

    for phase in exe.get("phases", []):
        add_heading_styled(phase.get("name", "Phase"), level=2)
        add_field("Timeline", phase.get("timeline", "TBD"))
        add_para(phase.get("description", ""), space_after=6)

        if phase.get("teams"):
            add_para("Team Assignments:", bold=True, size=11, space_after=2)
            for t in phase["teams"]:
                add_bullet(t)

        if phase.get("zone_assignments"):
            add_field("Zone Assignments", phase["zone_assignments"])
        doc.add_paragraph()

    add_divider()

    # ================================================================
    # IV. SUSTAINMENT
    # ================================================================
    sus = sop.get("sustainment", {})
    add_heading_styled("IV. Sustainment", level=1)

    # Personnel table
    pers = sus.get("personnel", {})
    if pers:
        add_heading_styled("Personnel", level=2)
        table = doc.add_table(rows=1, cols=2)
        table.style = "Light Grid Accent 1"
        table.alignment = WD_TABLE_ALIGNMENT.LEFT
        hdr = table.rows[0].cells
        hdr[0].text = "Role"
        hdr[1].text = "Count"
        for key, label in [
            ("assessment_teams", "Assessment Teams"),
            ("response_crews", "Response Crews"),
            ("logistics", "Logistics"),
            ("command", "Command"),
            ("total", "Total Core"),
            ("volunteer_surge", "Volunteer Surge"),
        ]:
            if key in pers:
                row = table.add_row().cells
                row[0].text = label
                row[1].text = str(pers[key])
        doc.add_paragraph()

    # Equipment
    if sus.get("equipment"):
        add_heading_styled("Equipment", level=2)
        for e in sus["equipment"]:
            add_bullet(e)

    # Materials
    if sus.get("materials"):
        add_heading_styled("Materials", level=2)
        for m in sus["materials"]:
            add_bullet(m)

    # Logistics
    if sus.get("logistics"):
        add_heading_styled("Logistics", level=2)
        add_para(sus["logistics"])

    add_divider()

    # ================================================================
    # V. COMMAND & SIGNAL
    # ================================================================
    cmd = sop.get("command_signal", {})
    add_heading_styled("V. Command & Signal", level=1)

    for key, label in [
        ("command_structure", "Command Structure"),
        ("reporting", "Reporting"),
        ("communications", "Communications"),
    ]:
        if cmd.get(key):
            add_heading_styled(label, level=2)
            add_para(cmd[key])

    if cmd.get("coordination"):
        add_heading_styled("Coordination", level=2)
        for c2 in cmd["coordination"]:
            add_bullet(c2)

    # ================================================================
    # APPENDIX: Priority Zones (if provided)
    # ================================================================
    if zones:
        doc.add_page_break()
        add_heading_styled("Appendix A: Priority Zone Rankings", level=1)

        table = doc.add_table(rows=1, cols=6)
        table.style = "Light Grid Accent 1"
        table.alignment = WD_TABLE_ALIGNMENT.LEFT
        hdr = table.rows[0].cells
        for i, h in enumerate(["Rank", "Zone", "Score", "SVI", "NRI", "Risk"]):
            hdr[i].text = h

        for z in zones:
            row = table.add_row().cells
            row[0].text = str(z.get("rank", ""))
            row[1].text = z.get("area_name", z.get("area", z.get("fips_tract", "")))
            row[2].text = str(z.get("composite_score", ""))
            row[3].text = f"{round((z.get('svi_score') or 0) * 100)}%"
            row[4].text = f"{round((z.get('nri_score') or 0) * 100)}%"
            row[5].text = z.get("risk_level", "")

    # -- Save to buffer --
    buffer = io.BytesIO()
    doc.save(buffer)
    buffer.seek(0)
    return buffer
